cam_collision_detector:
  ros__parameters:
    info_threshold_s: 15
    warn_threshold_s: 10
    fatal_threshold_s: 5
    prediction_horizon_s: 15
    collision_threshold_m: 2.5
    process_distance_threshold_m: 100
    ego_station_id: 28
    debug: true